apiVersion: v1
kind: ConfigMap
metadata:
  name: ota-config
data:
  POSTGRES_DB: ota_db
  POSTGRES_USER: otauser
  SERVER_URL: http://ota-server:5001
  DEVICE_ID: device-001
  POLL_INTERVAL: "10"
  INITIAL_VERSION: "1.0.0"